POST http://localhost:5000/api/users
Content-Type: application/json

{
    "email": "robert37@gmail.com",
    "first_name": "Kristy",
    "last_name": "Garcia",
    "username": "Kristy_Garcia",
    "password": "s4G0cv+u_q"
}